# Site settings
title: Codedge
email: henry@codedge.io
description: > # this means to ignore newlines until "baseurl:"
    Building awesome things, being edgy and stuff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codedge.io" # the base hostname & protocol for your site
github_username:  codedge-dev

# Build settings
markdown: kramdown
